loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/agents]
    modules: ['base', 'conversational', 'utils', 'agent_step', 'memory/conversation_memory', 'memory/conversation_summary_memory']
    ignore_when_discovered: ['__init__']
processors:
  - type: filter
    expression: "name not in ['print_text']"
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
   type: renderers.ReadmeRenderer
   excerpt: Uses a large language model to answer complex queries that require multiple steps to find the correct answer.
   category_slug: haystack-classes
   title: Agent API
   slug: agent-api
   order: 0
   markdown:
     descriptive_class_title: false
     descriptive_module_title: true
     add_method_class_prefix: true
     add_member_class_prefix: false
     filename: agent_api.md
