loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../haystack/evaluation]
    modules:
      [
        "base",
        "eval_run_result",
      ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Represents the results of evaluation.
  category_slug: haystack-api
  title: Evaluation
  slug: evaluation-api
  order: 61
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: evaluation_api.md
