loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../haystack/components/extractors]
    modules: ["named_entity_extractor"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: filter
    expression: "name not in ['_BackendEnumMeta', '_NerBackend', '_HfBackend', '_SpacyBackend']"
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Extracts predefined entities out of a piece of text.
  category_slug: haystack-api
  title: Extractors
  slug: extractors-api
  order: 65
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: extractors_api.md
