loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/pipelines]
    modules: ["base", "ray", "standard_pipelines"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression: "name not in ['_HaystackBeirRetrieverAdapter', '_RayDeploymentWrapper']"
  - type: filter
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmeRenderer
  excerpt: Arranges nodes in a predefined flow.
  category_slug: haystack-classes
  title: Pipelines API
  slug: pipelines-api
  order: 90
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: pipelines_api.md
