loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/nodes/retriever]
    modules: ["sparse", "dense", "multimodal/retriever", "web", "link_content"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmeRenderer
  excerpt: Sweeps through a document store and returns a set of candidate documents that are relevant to the query.
  category_slug: haystack-classes
  title: Retriever API
  slug: retriever-api
  order: 170
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: retriever_api.md
