loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../haystack/utils]
    ignore_when_discovered: ["__init__", "hf"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: filter
    expression: "name not in ['TokenSecret', 'EnvVarSecret','_get_default_device', '_split_device_string', 'convert']"
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmeCoreRenderer
  excerpt: Utility functions and classes used across the library.
  category_slug: haystack-api
  title: Utils
  slug: utils-api
  order: 153
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: utils_api.md
