name: Deploy website

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ master, benchmarks, generate_docstrings_locally ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'pydoc-markdown>=3.0.0,<4.0.0'
          pip install mkdocs
          pip install jupytercontrib

      # Generates the docstrings and tutorials so that we have the latest for the deployment
      - name: Generate Docstrings and Tutorials
        run: |
          cd docs/_src/api/api/
          ./generate_docstrings.sh 
          cd ../../tutorials/tutorials/
          python3 convert_ipynb.py  
          git status

      # Creates dispatch event for haystack-website repo
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: deepset-ai/haystack-website
          event-type: deploy-website
          client-payload: '{}'
