name: Docs Search Sync

on:
  pull_request:


jobs:
  docs-search-sync:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Haystack repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'


      - name: Install Docusaurus and build docs-website
        working-directory: haystack/docs-website
        run: |
          npm install
          npm run build



      # - name: Install python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: "3.11"

      # - name: Install dependencies
      #   run: pip install deepset-cloud-sdk

      # - name: Generate docs search feed
      #   env:
      #     WORKSPACE: ${{ secrets.DEEPSET_WORKSPACE_DOCS_SEARCH }}
      #     API_KEY: ${{ secrets.DEEPSET_API_KEY_DOCS_SEARCH }}
      #   run: python ./.github/utils/feed.py
