name: Add label on docstrings edit

on:
  pull_request_target:
    paths:
      - "haystack/**/*.py"
      - "rest_api/**/*.py"

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Copy file
        # We copy our script after base ref checkout so we keep executing
        # the same version even after checking out the HEAD ref.
        # This is done to prevent executing malicious code in forks' PRs.
        run: cp .github/utils/docstrings_checksum.py "${{ runner.temp }}/docstrings_checksum.py"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get docstrings
        id: base-docstrings
        run: |
          CHECKSUM=$(python "${{ runner.temp }}/docstrings_checksum.py" --root "${{ github.workspace }}")
          echo "checksum=$CHECKSUM" >> "$GITHUB_OUTPUT"

      - name: Checkout HEAD commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get docstrings
        id: head-docstrings
        run: |
          CHECKSUM=$(python "${{ runner.temp }}/docstrings_checksum.py" --root "${{ github.workspace }}")
          echo "checksum=$CHECKSUM" >> "$GITHUB_OUTPUT"

      - name: Check if we should label
        id: run-check
        run: echo "should_run=${{ steps.base-docstrings.outputs.checksum != steps.head-docstrings.outputs.checksum }}" >> "$GITHUB_OUTPUT"

      - name: Add label
        if: ${{ steps.run-check.outputs.should_run == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit ${{ github.event.pull_request.html_url }} --add-label "type:documentation"
