name: 'Stalebot'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  proposals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          only-labels: 'proposal'
          stale-pr-message: 'This proposal is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-stale: 30
          days-before-close: 10
