# If you change this name also do it in tests.yml and ci_metrics.yml
name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "**.py"
      - "!haystack/preview/**/*.py"  # See tests_preview.yml
      - "!test/preview/**/*.py"  # See tests_preview.yml
      - "!e2e/preview/**/*.py"  # See e2e_preview.yml
      - "pyproject.toml"
      - "!.github/**/*.py"
      - "!rest_api/**/*.py"
      - "!docs/**/*.py"

jobs:
  catch-all:
    name: Catch-all check
    runs-on: ubuntu-latest
    steps:
      - name: Skip tests
        run: echo "Skipped!"
